# Generated by Django 3.0.8 on 2020-07-03 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderNum', models.CharField(max_length=16, unique=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('first', models.CharField(default='', max_length=128)),
                ('last', models.CharField(default='', max_length=128)),
                ('email', models.EmailField(default='', max_length=128)),
                ('address', models.CharField(default='', max_length=128)),
                ('city', models.CharField(default='', max_length=128)),
                ('state', models.CharField(default='', max_length=2)),
                ('zipCode', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=1)),
                ('speed', models.CharField(default='', max_length=8)),
                ('color', models.CharField(default='', max_length=5)),
                ('layers', models.IntegerField(default=2)),
                ('gerber', models.FileField(storage='.../gerbers', upload_to='orders/gerbers/')),
            ],
        ),
    ]
