# Generated by Django 3.0.8 on 2020-08-01 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200704_1259'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gerber',
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='order',
            name='first',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='order',
            name='last',
            field=models.CharField(default='', max_length=32),
        ),
    ]
