# Generated by Django 3.1.1 on 2020-10-01 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20200818_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='silk',
            field=models.CharField(default='None', max_length=5),
        ),
        migrations.AlterField(
            model_name='order',
            name='zipCode',
            field=models.CharField(max_length=5),
        ),
    ]
