# Generated by Django 3.1.1 on 2020-10-02 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_order_silk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='layers',
        ),
        migrations.RemoveField(
            model_name='order',
            name='request',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
